### PR TITLE
Add/Update Lithuanian translation

### PR DESCRIPTION
**Pull request by welaq**

### CODE REVIEW

**Comment by peteruithoven** [comment]
Thanks! 
Your the first contributed translation so I'm very curious if you ran into issues? 
Also this reminded me that I didn't update the .pot file after 2 small text changes so I hope you can do another pull request afterwards.

**Comment by peteruithoven** [comment]
I've updated the translation files, could you update the fuzzy marked parts?
- https://github.com/peteruithoven/resizer/blob/master/po/lt.po#L28-L29
- https://github.com/peteruithoven/resizer/blob/master/po/lt.po#L33-L34

**Comment by welaq** [comment]
I didn't seem to have any issues.
Though I'm not sure whether you wanted app name "Resizer" to be translated or not. I have translated it for now. If you'd like to keep it "Resizer" in all languages I can revert translation.

**Comment by peteruithoven** [comment]
Also translating the app name sounds appropriate.
Seeing that you've contributed translations to many apps I'm curious what you think is "normal"? I can only imagine that brands wouldn't want this.

**Comment by welaq** [comment]
In this case I think it is a good idea to translate app name because the word is translatable. On the other hand it depends solely on developer, how he/she likes it.

**Pull request merged**
