### PR TITLE
Implements opening images using file chooser

### LINKED ISSUE #39: Enable adding images through file chooser
Enable adding images through file chooser
Docs: https://valadoc.org/gtk+-3.0/Gtk.FileChooserNative.html

### PR DESCRIPTION
**Pull request by Adithyan-KV**
closes #39 

Enables opening of images using file chooser native.

### CODE REVIEW

**Comment by Adithyan-KV** [comment]
Adds an insert button in the header bar which opens the file chooser dialog.

resizer_insert_button

**Comment by peteruithoven** [comment]
Nice! This is super handy. 
I would however like to do the UI slightly differently. I've now added some examples to the original issue: https://github.com/peteruithoven/resizer/issues/39#issuecomment-979384283

**Comment by Adithyan-KV** [comment]
Yeah I wasn't entirely sure of the UI either. Adding the button to the drop area does look much better. Will make the changes.

**Comment by Adithyan-KV** [comment]
One last question regarding the aesthetics though, With or without the suggested button accent color? The one without looks more minimal and preserves the neat aesthetic. But on the other hand the accent color is much more readable and adheres with the conventions in the rest of the system. 
resizer_ui_change

**Comment by peteruithoven** [comment]
Yeah I think it should have the accent colors because it's the most important action, it should kind of attract your attention. 
When you have selected images you'll also notice that the resize button gets the accent color.

**Comment by Adithyan-KV** [comment]
Yeah makes sense. I've made the changes.

**Comment by peteruithoven** [comment]
This seems to work great. 
Especially now that in elementary 6 we can't add a Resize images item to the files context menu this is a great feature.

**Pull request merged**
